### ISSUE TITLE
 RunExportEmissionsNetwork.java

### ISSUE THREAD

**Issue by neda-git** [eqasim-org/eqasim-java#164]
Hello @sebhoerl,
After updating the RunExportEmissionsNetwork.java, when I run that in command line:

java -cp ile_de_france-1.0.6.jar org.eqasim.ile_de_france.emissions.RunExportEmissionsNetwork --config-path config.xml --time-bin-size 3600

in output I have the shp file but the updated pollutants are not in this shape file. Could you please let me know what else i should do?

**Comment by sebhoerl** [comment]
Ah, I thought #163 was working. Please send a PR to revert it if it was not tested / didn't work. :)

I don't really work with this code, maybe @Nitnelav knows what to do? 

Looking at the code the pollutants come from `Map<Pollutant, Double> pollutants = emissions.getEmissions();`, so probably they need to be configured somewhere?

**Comment by neda-git** [comment]
Now, I got this message without returning me shp file:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Can handle 10 attributes only, index is 10
	at org.geotools.feature.simple.SimpleFeatureBuilder.set(SimpleFeatureBuilder.java:258)
	at org.geotools.feature.simple.SimpleFeatureBuilder.add(SimpleFeatureBuilder.java:202)
	at org.matsim.core.utils.gis.PolylineFeatureFactory.createPolyline(PolylineFeatureFactory.java:86)
	at org.matsim.core.utils.gis.PolylineFeatureFactory.createPolyline(PolylineFeatureFactory.java:80)
	at org.matsim.core.utils.gis.PolylineFeatureFactory.createPolyline(PolylineFeatureFactory.java:75)
	at org.eqasim.ile_de_france.emissions.RunExportEmissionsNetwork.main(RunExportEmissionsNetwork.java:97)
:(  Hope @Nitnelav can help me :)

**Comment by sebhoerl** [comment]
Okay, but next time please test before sending a PR. I'll revert the changes

**Comment by neda-git** [comment]
ok, sorry for bothering you. Thanks

**Comment by sebhoerl** [comment]
Closing this, checking the code it seems that this has been reverted. Please open again if the issue is not solved.
